name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc lcov libncurses5-dev cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: |
        cd build
        cmake -G "Unix Makefiles" ..

    - name: Build project
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        ctest -V

    - name: Capture coverage info
      run: |
        cd build
        lcov --directory . --capture --output-file coverage.info

    - name: Filter out system and test code
      run: |
        cd build
        lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info

    - name: List coverage info
      run: |
        cd build
        lcov --list coverage.info
