name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }} lcov libncurses5-dev

    - name: Build project
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
        make

    - name: Run tests with coverage
      run: |
        ./test-library.out --coverage

    - name: Capture coverage info
      run: |
        lcov --directory . --capture --output-file coverage.info

    - name: Filter out system and test code
      run: |
        lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info

    - name: List coverage info
      run: |
        lcov --list coverage.info

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.info
        flags: unittests
